#ifndef __CS_PARAMS_HPP_INCLUDED_
#define __CS_PARAMS_HPP_INCLUDED_

#define MAX_MICRO_BATCH_SIZE 500000
#define MAX_DATA_LENGTH 25
#define MAX_K_VALUE 20
#define MAX_R_VALUE 5
#define SLIDING_WINDOW_SIZE 5
#define MAX_WORKER_NUM 20 
#define STRAGGLER_THRESHOLD 2
#define MAX_MODEL_SIZE 256
#define SCALING_FACTOR 2

#endif

